//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperatorOverloading.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperatorOverloading.Model.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InvalidAmount: Amount Cannot be Negative.&quot;.
        /// </summary>
        internal static string AmountNegative {
            get {
                return ResourceManager.GetString("AmountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InvalidAmount: Amount is too large.&quot;.
        /// </summary>
        internal static string AmountTooLarge {
            get {
                return ResourceManager.GetString("AmountTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InvalidAmount: Please Enter Proper Amount Values.&quot;.
        /// </summary>
        internal static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InvalidCurrency: Input Currency Cannot be NULL.&quot;.
        /// </summary>
        internal static string InvalidCurrency {
            get {
                return ResourceManager.GetString("InvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;InvalidInput: Input Should be of type &lt;Amt&gt; &lt;Curr&gt;&quot;.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MismatchedCurrency: Please Enter Currency of the Same Type!!&quot;.
        /// </summary>
        internal static string MismatchedCurrency {
            get {
                return ResourceManager.GetString("MismatchedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Null Value in not Allowed.&quot;.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
    }
}
